{
 "title": "SYSMETRIX PULSE MONITOR",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cpu Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Real-time CPU Usage Overview",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 10, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_free_percent\n", "legendFormat": "CPU Free (%)" },
    { "expr": "cpu_usage_percent", "legendFormat": "CPU Usage (%)" }
   ]
  },
  {
   "title": "CPU Overall Free Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "cpu_free_percent", "legendFormat": "CPU Free (%)" }
   ]
  },
  {
   "title": "Cpu Overall Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "cpu_usage_percent\n", "legendFormat": "CPU Usage (%) " }
   ]
  },
  {
   "title": "App & Process-specific CPU Utilization",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(8, process_cpu_usage_percent{job=\"missing_semester_metrics\"})",
     "legendFormat": "{{process_name}},with pid {{pid}}"
    }
   ]
  },
  { "title": "Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Memory in Motion: Utilization and Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_usage_gegabytes", "legendFormat": "Memory Usage (GB)" },
    { "expr": "node_memory_free_gegabytes", "legendFormat": "Memory Free (GB)" }
   ]
  },
  {
   "title": "Free Memory Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    { "expr": "node_memory_free_gegabytes", "legendFormat": "Free Memory (GB)" }
   ]
  },
  {
   "title": "Memory Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    { "expr": "node_memory_usage_gegabytes", "legendFormat": "Used Memory (GB)" }
   ]
  },
  {
   "title": "App & Process-specific Memory Utilization",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "topk(8, process_memory_usage_megabytes{job=\"missing_semester_metrics\"})",
     "legendFormat": "{{process_name}} with pid {{pid}}"
    }
   ]
  },
  { "title": "DIsk Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Disk Device Distribution",
   "type": "bargauge",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_disk_device_devices", "legendFormat": "{{deviceName}}" }
   ]
  },
  {
   "title": "Partition Overview",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 57 },
   "targets": [
    { "expr": "node_disk_partitions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Read Rate per App",
   "type": "gauge",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, node_disk_read_bytes_rate_per_app)",
     "legendFormat": "{{process_name}}, with pid {{pid}}"
    }
   ]
  },
  {
   "title": "Disk Write Rate per App",
   "type": "gauge",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, node_disk_write_bytes_rate_per_app)",
     "legendFormat": "{{process_name}}, with pid {{pid}}"
    }
   ]
  }
 ]
}